### ISSUE TITLE
Config URI Error

### ISSUE THREAD

**Issue by InvalidUUID** [Auxes/Discord.Net-Example#15]
Hey,

Unsure if I'm doing something wrong or I am missing something, I cannot get the app to run.
Cloned it and put my token in the config however VS will not parse the YAML file no matter what I do to it.

Here's a log of the error;
```
System.FormatException
  HResult=0x80131537
  Message=Could not parse the YAML file: (Line: 1, Col: 9, Idx: 8) - (Line: 1, Col: 10, Idx: 9): While parsing a tag, did not find expected tag URI..
  Source=Microsoft.Extensions.Configuration.FileExtensions
  StackTrace:
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Example.Startup..ctor(String[] args) in C:\Users\Joey\Downloads\Discord.Net-Example-2.0\Discord.Net-Example-2.0\src\Startup.cs:line 20
   at Example.Startup.<RunAsync>d__4.MoveNext() in C:\Users\Joey\Downloads\Discord.Net-Example-2.0\Discord.Net-Example-2.0\src\Startup.cs:line 25
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Example.Program.<Main>(String[] args)

Inner Exception 1:
SyntaxErrorException: (Line: 1, Col: 9, Idx: 8) - (Line: 1, Col: 10, Idx: 9): While parsing a tag, did not find expected tag URI.
```

Any help maybe?

**Comment by InvalidUUID** [comment]
Solved it on my own, needed quotes around the exclamation mark.

**Comment by InvalidUUID** [comment]
Solved it on my own, needed quotes around the exclamation mark.
