### ISSUE TITLE
HelpModule Gives Me an Error

### ISSUE THREAD

**Issue by yellowface7** [Auxes/Discord.Net-Example#17]
`System.InvalidOperationException
  HResult=0x80131509
  Message=Failed to create "Example.Modules.HelpModule", dependency "IConfigurationRoot" was not found.
  Source=Discord.Net.Commands
  StackTrace:
   at Discord.Commands.ReflectionUtils.GetMember(CommandService commands, IServiceProvider services, Type memberType, TypeInfo ownerType)
   at Discord.Commands.ReflectionUtils.<>c__DisplayClass2_0`1.<CreateBuilder>b__0(IServiceProvider services)
   at Discord.Commands.ReflectionUtils.CreateObject[T](TypeInfo typeInfo, CommandService commands, IServiceProvider services)
   at Discord.Commands.Builders.ModuleBuilder.BuildImpl(CommandService service, IServiceProvider services, ModuleInfo parent)
   at Discord.Commands.ModuleClassBuilder.<BuildAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandService.<AddModulesAsync>d__35.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DbotTest.Program.<RegisterCommandsAsync>d__6.MoveNext() in C:\Users\Matthew\source\repos\DbotTest\Program.cs:line 56
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DbotTest.Program.<RunBotAsync>d__4.MoveNext() in C:\Users\Matthew\source\repos\DbotTest\Program.cs:line 38
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DbotTest.Program.Main(String[] args) in C:\Users\Matthew\source\repos\DbotTest\Program.cs:line 18

  This exception was originally thrown at this call stack:
	Discord.Commands.ReflectionUtils.GetMember(Discord.Commands.CommandService, System.IServiceProvider, System.Type, System.Reflection.TypeInfo)
	Discord.Commands.Builders.ModuleBuilder.BuildImpl(Discord.Commands.CommandService, System.IServiceProvider, Discord.Commands.ModuleInfo)
	Discord.Commands.ModuleClassBuilder.BuildAsync(System.Collections.Generic.IEnumerable<System.Reflection.TypeInfo>, Discord.Commands.CommandService, System.IServiceProvider)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	Discord.Commands.CommandService.AddModulesAsync(System.Reflection.Assembly, System.IServiceProvider)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    ...
    [Call Stack Truncated]
`

I guess this is what I get for doing a "copypasta". All I did was that I made a new cSharp class file and it would scream this at me every time I try to run the bot.

**Comment by Aux** [comment]
This isn't an issue with the example, but with your own personal code. Closing as irrelevant.
